# Generated by Django 3.0.7 on 2020-07-29 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_auto_20200726_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='selectType',
            field=models.CharField(default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='memo',
            field=models.CharField(max_length=200),
        ),
    ]
