# Generated by Django 3.0.7 on 2020-07-29 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0004_auto_20200730_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='selectType',
            field=models.CharField(default='Django', max_length=20),
        ),
    ]
